CLIENT_ID = 'Bjq8Z-x7Fg'
CLIENT_SECRET = 'K8k7sa1O4Wsfz_FLJDJ1VE2-RwheF93v_Ogg_u0CLyJvn7IEBvb-JkfP81ariUDLNWDy_hFSL7net6LL_HwG0oDEMS-uYgSL'
ENVIRONMENT = 'qa.'
ORGANIZATION_ID = 13355
ORGANIZATION_NAME = 'turbo'
USER_EMAIL = 'laurakirby26@gmail.com'
